version: "3.9"

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: interview_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

